[23.08.19 16:39:44:505]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-CharInfo:<init>(175)<-L2Player:newCharInfo(2551)<-L2Player:broadcastCharInfo(2563)<-L2ObjectTasks:runImpl(455)<-RunnableImpl:run(23)<-Executors:call(511)<-FutureTask:run$$$capture(266)<-FutureTask:run(-1)<-ScheduledThreadPoolExecutor:access$201(180)<-ScheduledThreadPoolExecutor:run(293)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:39:47:509]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:39:50:839]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:39:54:180]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:39:57:498]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:00:828]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:04:158]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:07:488]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:10:817]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:14:148]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:17:478]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:20:808]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:24:140]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:27:469]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:30:798]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:34:128]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:37:459]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:40:788]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:44:118]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:47:447]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:50:787]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:54:109]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:40:57:439]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:00:768]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:04:098]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:07:428]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:10:767]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:14:107]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:17:420]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:20:760]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:24:078]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:27:413]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:30:738]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:34:068]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:37:398]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:40:729]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:44:058]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:47:389]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:50:719]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:54:048]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:41:57:378]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:42:00:708]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.08.19 16:42:04:038]: Exception: RunnableImpl.run|Calculator:calc(191)<-L2Character:calcStat(929)<-L2Player:getMaxHp(11974)<-L2Player:checkHpMessages(8560)<-L2Character:runImpl(4501)<-RunnableImpl:run(23)<-SteppingRunnable:run(76)<-SteppingRunnable:run(228)<-Executors:call(511)<-FutureTask:runAndReset$$$capture(308)<-FutureTask:runAndReset(-1)<-ScheduledThreadPoolExecutor:access$301(180)<-ScheduledThreadPoolExecutor:run(294)<-ThreadPoolExecutor:runWorker(1149)<-ThreadPoolExecutor:run(624)<-Thread:run(750)<-
[23.11.22 15:43:22:047]: Exception: RunnableImpl.run|LastHunter:runImpl(62)<-RunnableImpl:run(23)<-Executors:call(511)<-FutureTask:run$$$capture(266)<-FutureTask:run(-1)<-ScheduledThreadPoolExecutor:access$201(180)<-ScheduledThreadPoolExecutor:run(293)<-ThreadPoolExecutor:runWorker(1142)<-ThreadPoolExecutor:run(617)<-Thread:run(745)<-
[23.11.22 16:08:27:688]: Exception: RunnableImpl.run|LastHunter:runImpl(62)<-RunnableImpl:run(23)<-Executors:call(511)<-FutureTask:run$$$capture(266)<-FutureTask:run(-1)<-ScheduledThreadPoolExecutor:access$201(180)<-ScheduledThreadPoolExecutor:run(293)<-ThreadPoolExecutor:runWorker(1142)<-ThreadPoolExecutor:run(617)<-Thread:run(745)<-
[23.11.22 16:13:58:185]: Exception: RunnableImpl.run|LastHunter:runImpl(62)<-RunnableImpl:run(23)<-Executors:call(511)<-FutureTask:run$$$capture(266)<-FutureTask:run(-1)<-ScheduledThreadPoolExecutor:access$201(180)<-ScheduledThreadPoolExecutor:run(293)<-ThreadPoolExecutor:runWorker(1142)<-ThreadPoolExecutor:run(617)<-Thread:run(745)<-
[23.11.22 17:22:09:694]: Exception: RunnableImpl.run|LastHunter:runImpl(62)<-RunnableImpl:run(23)<-Executors:call(511)<-FutureTask:run$$$capture(266)<-FutureTask:run(-1)<-ScheduledThreadPoolExecutor:access$201(180)<-ScheduledThreadPoolExecutor:run(293)<-ThreadPoolExecutor:runWorker(1142)<-ThreadPoolExecutor:run(617)<-Thread:run(745)<-
[23.11.24 19:45:04:709]: Exception: RunnableImpl.run|LastHunter:runImpl(62)<-RunnableImpl:run(23)<-Executors:call(511)<-FutureTask:run$$$capture(266)<-FutureTask:run(-1)<-ScheduledThreadPoolExecutor:access$201(180)<-ScheduledThreadPoolExecutor:run(293)<-ThreadPoolExecutor:runWorker(1142)<-ThreadPoolExecutor:run(617)<-Thread:run(745)<-
